CreateClientConVar("fm_k_playermodel", "models/player/alyx.mdl", true, true)
CreateClientConVar("fm_k_playerskin", "0", true, true)
CreateClientConVar("fm_k_propmenu_sort", "0", true, true)
CreateClientConVar("fm_k_propmenu_filter", "0", true, true)
CreateClientConVar("fm_k_weapmenu_sort", "0", true, true)
CreateClientConVar("fm_k_weapmenu_filter", "0", true, true)